---
# ConfigMap para user-service
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: default
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8081"

---
# Secret para user-service
apiVersion: v1
kind: Secret
metadata:
  name: user-secret
  namespace: default
type: Opaque
stringData:
  # ⚠️ REEMPLAZA con tu endpoint de RDS
  DB_URL: "jdbc:postgresql://userdb.cvpunkj36v2t.us-east-1.rds.amazonaws.com:5432/userdb"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
